---
# tasks file for ansible-role-shellcheck

- name: Getting latest shellcheck version
  shell: | # noqa 303
    set -o pipefail
    git ls-remote --sort='v:refname' --tags https://github.com/koalaman/shellcheck.git | tail -n1 | sed 's/.*\///; s/\^{}//' | sed 's/v//'
  register: shellcheck_git
  changed_when: false

- name: Removing any shellcheck package
  package:
      state: absent
      name: "{{ item }}"
  loop:
    - shellcheck
    - ShellCheck

- name: Checking if shellcheck is installed
  stat:
    path: /usr/bin/shellcheck
  register: shellcheck_installed

- name: Getting current shellcheck version
  shell: |
    set -o pipefail
    /usr/bin/shellcheck --version | grep "version:" | cut -c10-
  when: shellcheck_installed.stat.exists
  register: shellcheck_local
  changed_when: false

- name: Set forced version
  set_fact:
    shellcheck_git_version: "{{ shellcheck_install_version }}"
  when: shellcheck_force_install | bool

- name: Set latest git version
  set_fact:
    shellcheck_git_version: "{{ shellcheck_git.stdout }}"
  when: not shellcheck_force_install

- name: Set local version
  set_fact:
    shellcheck_local_version: "{{ shellcheck_local.stdout }}"
  when: shellcheck_installed.stat.exists

- include_tasks: uninstall.yml
  when:
    - shellcheck_installed.stat.exists
    - (shellcheck_git_version != shellcheck_local_version) or shellcheck_force_install

- include_tasks: install.yml
  when: not shellcheck_installed.stat.exists or
        shellcheck_force_install or
        (shellcheck_git_version != shellcheck_local_version)